In [15]:
import os
import sys

print("현재 작업 위치:", os.getcwd())
print("Python 실행 위치:", sys.executable)

현재 작업 위치: /home/yongbin/projects/rna-seq-variant-portfolio/human_lps/notebooks
Python 실행 위치: /home/yongbin/projects/rna-seq-variant-portfolio/human_lps/.venv/bin/python

In [16]:
import os

print(os.path.exists("../results/count_matrix.csv"))
print(os.path.exists("../metadata/sample_metadata.csv"))

True
True

In [17]:
import pandas as pd

deg_results = pd.read_csv("../results/tables/deseq2_results_LPS_vs_Control.csv")
sig_deg = pd.read_csv("../results/tables/significant_DEG_padj_0.05.csv")

display(deg_results.head())
display(sig_deg)

print("전체 gene 수:", deg_results.shape[0])
print("유의 DEG 수:", sig_deg.shape[0])

deg_results.head(10)

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSG00000229807,660.236493,10.775745,1.950467,5.524700,3.300487e-08,0.000737
1,ENSG00000275294,923.503822,6.973573,1.669157,4.177902,2.942103e-05,0.328692
2,ENSG00000228037,35.207478,-0.591529,1.136347,-0.520554,6.026777e-01,0.999955
3,ENSG00000142611,2.152924,-0.342624,1.883232,-0.181934,8.556343e-01,0.999955
4,ENSG00000157911,129.344491,0.075255,0.339948,0.221372,8.248026e-01,0.999955

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSG00000229807,660.236493,10.775745,1.950467,5.5247,3.300487e-08,0.000737

전체 gene 수: 22505
유의 DEG 수: 1

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSG00000229807,660.236493,10.775745,1.950467,5.524700,3.300487e-08,0.000737
1,ENSG00000275294,923.503822,6.973573,1.669157,4.177902,2.942103e-05,0.328692
2,ENSG00000228037,35.207478,-0.591529,1.136347,-0.520554,6.026777e-01,0.999955
3,ENSG00000142611,2.152924,-0.342624,1.883232,-0.181934,8.556343e-01,0.999955
4,ENSG00000157911,129.344491,0.075255,0.339948,0.221372,8.248026e-01,0.999955
5,ENSG00000228463,22.874394,0.298015,1.027186,0.290128,7.717183e-01,0.999955
6,ENSG00000142655,264.484045,0.050123,0.492283,0.101818,9.189012e-01,0.999955
7,ENSG00000149527,9.176375,-0.253979,0.732235,-0.346855,7.287003e-01,0.999955
8,ENSG00000171621,1249.767139,-1.256866,0.881422,-1.425953,1.538820e-01,0.999955
9,ENSG00000272235,5.227962,-1.713345,1.506148,-1.137567,2.553013e-01,0.999955

In [18]:
import pandas as pd

deg_results = pd.read_csv("../results/tables/deseq2_results_LPS_vs_Control.csv")

# 첫 번째 열 이름 변경
deg_results.rename(
    columns={"Unnamed: 0": "Geneid"},
    inplace=True
)

deg_results.head()

,Geneid,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSG00000229807,660.236493,10.775745,1.950467,5.524700,3.300487e-08,0.000737
1,ENSG00000275294,923.503822,6.973573,1.669157,4.177902,2.942103e-05,0.328692
2,ENSG00000228037,35.207478,-0.591529,1.136347,-0.520554,6.026777e-01,0.999955
3,ENSG00000142611,2.152924,-0.342624,1.883232,-0.181934,8.556343e-01,0.999955
4,ENSG00000157911,129.344491,0.075255,0.339948,0.221372,8.248026e-01,0.999955

In [19]:
deg_results[deg_results["Geneid"] == "ENSG00000136244"]

,Geneid,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
8797,ENSG00000136244,150603.918987,-0.348671,1.919914,-0.181608,0.855891,0.999955

In [20]:
deg_results[deg_results["Geneid"] == "ENSG00000169429"]

,Geneid,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
5574,ENSG00000169429,1.841920e+06,0.017007,1.344449,0.01265,0.989907,0.999955

In [21]:
deg_results[deg_results["Geneid"] == "ENSG00000100906"]

,Geneid,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
15730,ENSG00000100906,133253.066174,0.085993,0.883058,0.097381,0.922424,0.999955

In [22]:
#면역 유전자 ID 목록 만들기
immune_gene_map = pd.DataFrame({
    "Geneid": [
        "ENSG00000136244",  # IL6
        "ENSG00000169429",  # CXCL8
        "ENSG00000100906",  # NFKBIA
        "ENSG00000228978",  # TNF candidate
        "ENSG00000204490",  # TNF candidate
        "ENSG00000228849",  # TNF candidate
        "ENSG00000223952",  # TNF candidate
        "ENSG00000228321",  # TNF candidate
        "ENSG00000230108",  # TNF candidate
        "ENSG00000206439",  # TNF candidate
        "ENSG00000232810"   # TNF candidate
    ],
    "gene_symbol": [
        "IL6",
        "CXCL8",
        "NFKBIA",
        "TNF",
        "TNF",
        "TNF",
        "TNF",
        "TNF",
        "TNF",
        "TNF",
        "TNF"
    ]
})

immune_gene_map

             Geneid gene_symbol
0   ENSG00000136244         IL6
1   ENSG00000169429       CXCL8
2   ENSG00000100906      NFKBIA
3   ENSG00000228978         TNF
4   ENSG00000204490         TNF
5   ENSG00000228849         TNF
6   ENSG00000223952         TNF
7   ENSG00000228321         TNF
8   ENSG00000230108         TNF
9   ENSG00000206439         TNF
10  ENSG00000232810         TNF

In [23]:
#DESeq2 결과와 면역 유전자 표 합치기
immune_deg_results = immune_gene_map.merge(
    deg_results,
    on="Geneid",
    how="left"
)

immune_deg_results

,Geneid,gene_symbol,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSG00000136244,IL6,1.506039e+05,-0.348671,1.919914,-0.181608,0.855891,0.999955
1,ENSG00000169429,CXCL8,1.841920e+06,0.017007,1.344449,0.012650,0.989907,0.999955
2,ENSG00000100906,NFKBIA,1.332531e+05,0.085993,0.883058,0.097381,0.922424,0.999955
3,ENSG00000228978,TNF,NaN,NaN,NaN,NaN,NaN,NaN
4,ENSG00000204490,TNF,NaN,NaN,NaN,NaN,NaN,NaN
5,ENSG00000228849,TNF,NaN,NaN,NaN,NaN,NaN,NaN
6,ENSG00000223952,TNF,NaN,NaN,NaN,NaN,NaN,NaN
7,ENSG00000228321,TNF,NaN,NaN,NaN,NaN,NaN,NaN
8,ENSG00000230108,TNF,NaN,NaN,NaN,NaN,NaN,NaN
9,ENSG00000206439,TNF,NaN,NaN,NaN,NaN,NaN,NaN
10,ENSG00000232810,TNF,7.590951e+04,-0.644645,1.515187,-0.425455,0.670505,0.999955

In [24]:
#필요한 열만 보기 좋게 정리
immune_deg_summary = immune_deg_results[
    [
        "gene_symbol",
        "Geneid",
        "baseMean",
        "log2FoldChange",
        "lfcSE",
        "stat",
        "pvalue",
        "padj"
    ]
]

immune_deg_summary

,gene_symbol,Geneid,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,IL6,ENSG00000136244,1.506039e+05,-0.348671,1.919914,-0.181608,0.855891,0.999955
1,CXCL8,ENSG00000169429,1.841920e+06,0.017007,1.344449,0.012650,0.989907,0.999955
2,NFKBIA,ENSG00000100906,1.332531e+05,0.085993,0.883058,0.097381,0.922424,0.999955
3,TNF,ENSG00000228978,NaN,NaN,NaN,NaN,NaN,NaN
4,TNF,ENSG00000204490,NaN,NaN,NaN,NaN,NaN,NaN
5,TNF,ENSG00000228849,NaN,NaN,NaN,NaN,NaN,NaN
6,TNF,ENSG00000223952,NaN,NaN,NaN,NaN,NaN,NaN
7,TNF,ENSG00000228321,NaN,NaN,NaN,NaN,NaN,NaN
8,TNF,ENSG00000230108,NaN,NaN,NaN,NaN,NaN,NaN
9,TNF,ENSG00000206439,NaN,NaN,NaN,NaN,NaN,NaN
10,TNF,ENSG00000232810,7.590951e+04,-0.644645,1.515187,-0.425455,0.670505,0.999955

In [25]:
#결과 저장
immune_deg_summary.to_csv(
    "../results/tables/immune_gene_DESeq2_summary.csv",
    index=False
)

In [26]:
#저장 확인
pd.read_csv("../results/tables/immune_gene_DESeq2_summary.csv")

,gene_symbol,Geneid,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,IL6,ENSG00000136244,1.506039e+05,-0.348671,1.919914,-0.181608,0.855891,0.999955
1,CXCL8,ENSG00000169429,1.841920e+06,0.017007,1.344449,0.012650,0.989907,0.999955
2,NFKBIA,ENSG00000100906,1.332531e+05,0.085993,0.883058,0.097381,0.922424,0.999955
3,TNF,ENSG00000228978,NaN,NaN,NaN,NaN,NaN,NaN
4,TNF,ENSG00000204490,NaN,NaN,NaN,NaN,NaN,NaN
5,TNF,ENSG00000228849,NaN,NaN,NaN,NaN,NaN,NaN
6,TNF,ENSG00000223952,NaN,NaN,NaN,NaN,NaN,NaN
7,TNF,ENSG00000228321,NaN,NaN,NaN,NaN,NaN,NaN
8,TNF,ENSG00000230108,NaN,NaN,NaN,NaN,NaN,NaN
9,TNF,ENSG00000206439,NaN,NaN,NaN,NaN,NaN,NaN
10,TNF,ENSG00000232810,7.590951e+04,-0.644645,1.515187,-0.425455,0.670505,0.999955

In [27]:
#DESeq2 분석은 정상적으로 실행됨
#↓
#유의 DEG는 XIST 1개
#↓
#대표 LPS 면역 유전자 IL6, CXCL8, NFKBIA는 유의하지 않음
#↓
#TNF 후보 ID들을 추가 확인해야 함
#↓
#샘플 조건/metadata 검증이 필요함

In [1]:
import pandas as pd

# 1. Load DESeq2 result files
deg_results = pd.read_csv("../results/tables/deseq2_results_LPS_vs_Control.csv")
sig_deg = pd.read_csv("../results/tables/significant_DEG_padj_0.05.csv")

# 2. Clean column name
deg_results = deg_results.rename(columns={"Unnamed: 0": "Geneid"})
sig_deg = sig_deg.rename(columns={"Unnamed: 0": "Geneid"})

# 3. Define immune-response marker genes
immune_gene_map = pd.DataFrame({
    "Geneid": [
        "ENSG00000136244",  # IL6
        "ENSG00000169429",  # CXCL8
        "ENSG00000100906",  # NFKBIA
        "ENSG00000232810"   # TNF, main candidate from biomaRt result
    ],
    "gene_symbol": [
        "IL6",
        "CXCL8",
        "NFKBIA",
        "TNF"
    ]
})

# 4. Merge immune gene list with DESeq2 results
immune_deg_summary = immune_gene_map.merge(
    deg_results,
    on="Geneid",
    how="left"
)

# 5. Select key columns
immune_deg_summary = immune_deg_summary[
    [
        "gene_symbol",
        "Geneid",
        "baseMean",
        "log2FoldChange",
        "lfcSE",
        "stat",
        "pvalue",
        "padj"
    ]
]

# 6. Save summary table
immune_deg_summary.to_csv(
    "../results/tables/immune_gene_DESeq2_summary.csv",
    index=False
)

# 7. Display results
print("Number of total genes:", deg_results.shape[0])
print("Number of significant DEGs:", sig_deg.shape[0])

display(sig_deg)
display(immune_deg_summary)

Number of total genes: 22505
Number of significant DEGs: 1

,Geneid,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,ENSG00000229807,660.236493,10.775745,1.950467,5.5247,3.300487e-08,0.000737

,gene_symbol,Geneid,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,IL6,ENSG00000136244,1.506039e+05,-0.348671,1.919914,-0.181608,0.855891,0.999955
1,CXCL8,ENSG00000169429,1.841920e+06,0.017007,1.344449,0.012650,0.989907,0.999955
2,NFKBIA,ENSG00000100906,1.332531e+05,0.085993,0.883058,0.097381,0.922424,0.999955
3,TNF,ENSG00000232810,7.590951e+04,-0.644645,1.515187,-0.425455,0.670505,0.999955